# Multiple Linear Regression

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [11]:
dataset=pd.read_csv('Data.csv')
X= dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1:].values

## Splitting the dataset into the Training set and Test set

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=0)
#y_train[:4]

array([[473.93],
       [467.87],
       [431.97],
       [425.28]])

## Training the Multiple Linear Regression model on the Training set

In [20]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [23]:
y_pred = regressor.predict(X_test)
print(y_pred[:4])
print(y_test[:4])

[[431.42761597]
 [458.56124622]
 [462.75264705]
 [448.59596206]]
[[431.23]
 [460.01]
 [461.14]
 [445.9 ]]


## Evaluating the Model Performance

In [24]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9325315554761303