# Logistic Regression

## Importing the libraries

In [35]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [36]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state = 0)

## Feature Scaling

In [68]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [69]:
print(X_train[:5],'\n',y_train[:5])

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]] 
 [0 1 0 1 1]


In [70]:
print(X_test[:5],'\n',y_test[:5])

[[-0.80480212  0.50496393]
 [-0.01254409 -0.5677824 ]
 [-0.30964085  0.1570462 ]
 [-0.80480212  0.27301877]
 [-0.30964085 -0.5677824 ]] 
 [0 0 0 0 0]


## Training the Logistic Regression model on the Training set

In [45]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting a new result

In [72]:
print(classifier.predict(scaler.transform([[30,87000]])))
print(classifier.predict_proba(scaler.transform([[30,87000]])))

[0]
[[0.87403368 0.12596632]]


## Predicting the Test set results

In [80]:
y_pred = (classifier.predict(X_test))
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0
 0 0 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1]


## Confusion Matrix for Binary classification(from scratch)

In [ ]:
corr_one = 0
corr_zero = 0
wr_one = 0
wr_zero = 0
for i in range(0,len(y_pred)):
    if(y_pred[i]==y_test[i]):
        if(y_pred[i]==1):
            corr_one+=1
        else:
            corr_zero+=1
    else:
        if(y_test[i]==1):
            wr_one+=1
        else:
            wr_zero+=1
print('corr_one',corr_one,'corr_zero',corr_zero,'wr_one',wr_one,'wr_zero',wr_zero)

## Making the Confusion Matrix

In [84]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred,y_test)
score = accuracy_score(y_pred, y_test)
print(cm)
print(score)

[[65  8]
 [ 3 24]]
0.89
